//! The `--resource` registry: descriptors, dispatch and law tests from one
//! list.

use crate::{
    b::B, bound_error::BoundError, dioid::Dioid, max_plus::MaxPlus,
    resource_descriptor::ResourceDescriptor, resource_id::ResourceId,
};

/// Declares the `--resource` surface.
///
/// Emits, from one list:
///
/// 1. [`ResourceKind`], a closed enum. **Not `#[non_exhaustive]`**, so a
///    downstream `match` that dispatches on it fails to compile when an entry
///    is added. Without that, adding a fifth resource makes `--help` list it
///    and the unknown-value error mention it while the dispatch `match` falls
///    through to a wildcard - a "not implemented" error, or a panic, for a
///    resource the tool advertises.
/// 2. [`registered`], the ordered descriptor slice `--help` and
///    [`BoundError::UnknownResource`] are both generated from.
/// 3. `check_all_registered_laws`, which calls the law suite for each entry's
///    semiring - so registering a semiring that does not implement
///    `DioidLaws` is a compile error, and no entry can exist without its laws
///    being run.
macro_rules! register_resources {
    ( $( $variant:ident => $cli:literal : $semiring:ty { unit: $unit:literal, summary: $summary:literal } ),+ $(,)? ) => {
        /// Every resource `--resource` accepts.
        ///
        /// Generated by `register_resources!`. Deliberately closed: adding an
        /// entry must be a compile error at every dispatch site.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum ResourceKind {
            $(
                #[doc = $summary]
                $variant,
            )+
        }

        impl ResourceKind {
            /// Every registered resource, in registration order.
            pub const ALL: &'static [ResourceKind] = &[ $( ResourceKind::$variant ),+ ];

            /// This resource's descriptor.
            #[must_use]
            pub const fn descriptor(self) -> ResourceDescriptor {
                match self {
                    $(
                        ResourceKind::$variant => ResourceDescriptor::new(
                            ResourceId::new($cli),
                            <$semiring as Dioid>::SEMIRING,
                            $unit,
                            $summary,
                        ),
                    )+
                }
            }

            /// The `--resource` value naming this resource.
            #[must_use]
            pub const fn id(self) -> ResourceId {
                self.descriptor().id()
            }

            /// Every registered `--resource` value, in registration order.
            #[must_use]
            pub fn registered_names() -> Vec<&'static str> {
                vec![ $( $cli ),+ ]
            }

            /// Parses a `--resource` value.
            ///
            /// # Errors
            ///
            /// [`BoundError::UnknownResource`], carrying the registered set
            /// generated from this same list.
            pub fn parse(value: &str) -> Result<Self, BoundError> {
                match value {
                    $( $cli => Ok(ResourceKind::$variant), )+
                    other => Err(BoundError::UnknownResource {
                        got: other.to_owned(),
                        known: Self::registered_names(),
                    }),
                }
            }
        }

        /// Every registered resource's descriptor, in registration order.
        ///
        /// An ordered slice, never a hash container, so `--help` and the
        /// unknown-value message are byte-identical on every run.
        #[must_use]
        pub fn registered() -> &'static [ResourceDescriptor] {
            static DESCRIPTORS: &[ResourceDescriptor] =
                &[ $( ResourceKind::$variant.descriptor() ),+ ];
            DESCRIPTORS
        }

        /// Runs the frozen law suite for every registered resource's semiring.
        ///
        /// # Errors
        ///
        /// The first law violation found.
        #[cfg(any(test, feature = "laws"))]
        pub fn check_all_registered_laws() -> Result<(), crate::law_failure::LawFailure> {
            $( crate::dioid_laws::check_dioid_laws::<$semiring>()?; )+
            Ok(())
        }
    };
}

register_resources! {
    Ops     => "ops"      : B       { unit: "operations",  summary: "abstract operation count" },
    Alloc   => "alloc"    : B       { unit: "allocations", summary: "total bytes allocated" },
    PeakMem => "peak-mem" : MaxPlus { unit: "bytes",       summary: "peak live memory" },
    Queries => "queries"  : B       { unit: "queries",     summary: "external calls issued" },
}

#[cfg(test)]
mod frozen_registry {
    use super::{ResourceKind, registered};

    #[test]
    fn resource_surface_is_pinned() {
        assert_eq!(
            ResourceKind::registered_names(),
            vec!["ops", "alloc", "peak-mem", "queries"]
        );
        assert_eq!(registered().len(), 4);
        // Three resources, one algebra: this is exactly why the cache key is
        // built from `ResourceId` and never from `SemiringId`.
        assert_eq!(
            ResourceKind::Ops.descriptor().semiring(),
            ResourceKind::Alloc.descriptor().semiring()
        );
        assert_ne!(ResourceKind::Ops.id(), ResourceKind::Alloc.id());
    }
}
